### ISSUE TITLE
Building under OSX with Homebrew

### ISSUE THREAD

**Issue by paines** [AlexCharlton/Hypergiant#1]
In order to get things compiled under OSX(tested under yosemite) with Homebrew, some manual work has to be done.

Besides installing all dependencies (GLFW3,...) , one needs to create a symbolic for libglfw.dylib.
e.g: 
cd /usr/local/lib 
ln -s ../Cellar/glfw3/3.0.4/lib/libglfw3.dylib libglfw.dylib

The other thing is the SOIL egg. Download it via chicken-install -r soil
and then patch the file soil.setup to add "-framework CoreFoundation" for the macosx section:
e.g.:
chicken-install -r soil
cd soil
edit soil.setup
....
.... 
(define compile-options
  (cond-expand
    (macosx "-FOpenGL -FSOIL -framework CoreFoundation ")
    (else "")))

....
....
save and do sudo chicken-install from within soil directory. After that, procede with sudo chicken-install hypergiant.

**Comment by AlexCharlton** [comment]
Thanks for the report, @paines. As I'm sure you know, those eggs are both seperate projects with their own repositories, so the fixes will go there. The issue with soil is already fixed, and just waiting to be pulled to the master repo. I'm going to investigate the glfw3 issue this weekend, so expect a fix for that soon, as well!

**Comment by AlexCharlton** [comment]
An update on things, @paines:

The issue with glfw3 is the fault of Homebrew, and as such I won't be updating the glfw3 egg. They patch GLFW's source to change the library's name for reasons that are beyond me. I've added a note about installing GLFW with Homebrew in the documentation, though, so thanks for the report!
