### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by kristianlm** [AlexCharlton/Hypergiant#8]
Hey Alex!

When doing `chicken-install hypergiant`, I get this:

```
Warning: reference to possibly unbound identifier `pixel-density-ratio' in:
Warning:    start*
```

I believe this should fix it:

``` patch
--- a/window.scm
+++ b/window.scm
@@ -91,5 +91,5 @@
   (resize #f width height)
   (set-pixel-density-ratio)
-  (pixel-density-ratio (ceiling *pixel-density-ratio*))
+  (set! *pixel-density-ratio* (ceiling *pixel-density-ratio*))
   (gl:get-error) ;; silence error caused by GLEW
   (glls:compile-pipelines)
```

I felt forking was a bit overkill for this one.

**Comment by AlexCharlton** [comment]
While the code isn't very clear, the `pixel-density-ratio` being referenced there is a parameter from `gl-type`. You probably have an old version lying around (not being able to version dependencies in Chicken is a real pain), so `chicken-install gl-type hypergiant` should work!

**Comment by kristianlm** [comment]
Ah, indeed!

I believe you can do this:

``` patch
--- a/hypergiant.meta
+++ b/hypergiant.meta
@@ -7 +7 @@
- (depends  glfw3 glls opengl-glew gl-math gl-utils gl-type hyperscene
+ (depends  glfw3 glls opengl-glew gl-math gl-utils (gl-type 0.2.1) hyperscene
```

**Comment by AlexCharlton** [comment]
Oh wow, you can! This changes everything!

**Comment by dleslie** [comment]
Oooh
